%% need no \usepackage{Sweave.sty}
<<setup,cache=FALSE,include=FALSE>>=
source("setup.R")
@


\section{Outlook} \label{sec:outlook}

%      - weitere Anwendungsgebiete über infektiöse Krankheiten
%      - Möglichkeit manche der Modellierung ein einen
% Ausbruchsdetektionskontext
%        zu setzen





This paper will be included as a vignette in the \pkg{surveillance} package, where it will be kept up-to-date with the software.
