# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

determineSourcesC <- function(eventTimes, eps_t, eventCoords, eps_s, eventTypes, qmatrix) {
    .Call('surveillance_determineSourcesC', PACKAGE = 'surveillance', eventTimes, eps_t, eventCoords, eps_s, eventTypes, qmatrix)
}

