---
title: Events
---

## 2020

- The **surveillance** package is part of the COVID-19 outbreak response.
  For example:

  - The `nowcast()` function is used to provide situational awareness,
    both in [Bavaria](https://corona.stat.uni-muenchen.de/nowcast/)
    and in [Berlin](https://www.berlin.de/corona/lagebericht/desktop/corona.html).

  - The `hhh4()` modelling framework has been used in several
    retrospective studies of disease dynamics in
```{r, echo = FALSE, results = "asis"}
refs_EE <- read.csv("../../../www/applications_EE.csv")
knitr::combine_words(
  with(subset(refs_EE, Model == "hhh4" & Disease == "COVID-19"),
       sprintf("[%s](%s)", Location, URL))
)
```

## 2019

- The [*Handbook of Infectious Disease Data Analysis*](https://doi.org/10.1201/9781315222912)
  features the **surveillance** package in several chapters of Part V
  ("Analysis of Surveillance Data"):
  
  - `twinstim()` is mentioned in Chapter 20 on
    "Applications of Point Process Methods" by Peter J. Diggle.

  - The `?imdepi` data is used to illustrate prospective outbreak detection
    methods, such as `earsC()`, `farrington()`/`farringtonFlexible()`, and
    `stcd()`, in Chapter 21 by Benjamin Allévius and Michael Höhle
    (see [replication code](https://github.com/BenjaK/ProspectiveDetectionChapter)).

  - `bodaDelay()` is mentioned in Chapter 22 on "Underreporting and
    Reporting Delays" by Angela Noufaily.
  
  - `hhh4()` is discussed and applied with a focus on
    - spatio-temporal modelling in Chapter 23 by Jon Wakefield et al., see
      the [replication code](https://arxiv.org/src/1711.00555v1/anc)
      applied to the `?measlesWeserEms` data
    - forecasting in Chapter 25 by Leonhard Held and Sebastian Meyer, see
      the [replication code](https://hidda.github.io/forecasting/)
      applied to count time series of
      [ILI in Switzerland](https://hidda.github.io/forecasting/reference/CHILI.html)
      and [norovirus gastroenteritis in Berlin](https://hidda.github.io/forecasting/articles/BNV_files/figure-html/BNV_stsplot-1.png)
      (from `hhh4contacts::noroBE()`)

- The paper
  [*Endemic-epidemic models with discrete-time serial interval distributions for infectious disease prediction*](https://arxiv.org/abs/1901.03090)
  describes an extension of `hhh4()` for distributed lags
  as implemented in the
  [**hhh4addon**](https://github.com/jbracher/hhh4addon) package by
  Johannes Bracher.

## 2017

- 2017/05/03: A standard reference describing the spatio-temporal modelling
  frameworks of the package has appeared in the Journal of Statistical Software:
  <https://doi.org/10.18637/jss.v077.i11>.
  Sections 3 to 5 of this paper are available as
  - [`vignette("twinstim", package = "surveillance")`](https://CRAN.R-project.org/package=surveillance/vignettes/twinstim.pdf)
    to analyze a spatio-temporal point pattern of infective events
  - [`vignette("twinSIR", package = "surveillance")`](https://CRAN.R-project.org/package=surveillance/vignettes/twinSIR.pdf)
    to analyze the susceptible-infectious-recovered (SIR) event history of a fixed population
  - [`vignette("hhh4_spacetime", package = "surveillance")`](https://CRAN.R-project.org/package=surveillance/vignettes/hhh4_spacetime.pdf)
    to analyze areal time series of infectious disease counts

## 2016

- 2016/11/30: We arranged a small surveillance hackathon as part of the
  ESCAIDE 2016 conference in Stockholm, Sweden. One output is a set of
  [tutorials](https://surveillancer.github.io/tutorials/) on how to use
  the package.

- 2016/05/20: A standard reference describing the monitoring aspects of the
  package has appeared in the Journal of Statistical Software:
  <https://doi.org/10.18637/jss.v070.i10>.
  This paper is also available as
  [`vignette("monitoringCounts", package = "surveillance")`](https://CRAN.R-project.org/package=surveillance/vignettes/monitoringCounts.pdf).

- 2016/04/13: A paper on [model-based testing for space-time interaction using
  point processes](https://doi.org/10.1016/j.sste.2016.03.002)
  describes a new global test for clustering based on the endemic-epidemic point
  process model `twinstim()`.

- 2016/03/31: The paper [*A system for automated outbreak detection of communicable
  diseases in Germany*](https://doi.org/10.2807/1560-7917.ES.2016.21.13.30180)
  describes use of the package as backbone for the German infectious
  disease monitoring system.

- 2016/01/21: The paper [*Bayesian nowcasting during the STEC O104:H4 outbreak in
  Germany, 2011*](https://doi.org/10.1111/biom.12194),
  which builds on the **surveillance** package, won the **Best 2014 Paper in
  Biometrics by an IBS member** award. The award will be given at the
  IBC 2016 in Victoria, Canada.

## 2015

- 2015/12/03: Working paper on incorporating age-structured social
  contact data in the spatio-temporal `hhh4` model for stratified, areal
  time series of infectious disease counts: <https://arxiv.org/abs/1512.01065>

- 2015/09/21: ISDS Webinar on *Aberration Detection in Public Health
  Surveillance using the R package `surveillance`*.
  ([recording](https://vimeo.com/140669369),
  [material](https://sites.google.com/site/rapplicationforbiosurveillance/home/meetings))
  
- 2015/07/01: Two talks about the **surveillance** package given at the
  [useR2015!](https://user2015.math.aau.dk) conference:
  - [*Zombie Preparedness*](https://staff.math.su.se/hoehle/software/surveillance/hoehle-userR2015-web.pdf)
    by Michael H&ouml;hle
  - [*Spatio-Temporal Analysis of Epidemic Phenomena Using the R Package
    surveillance*](https://user2015.math.aau.dk/presentations/40.pdf)
    by Sebastian Meyer

## 2014

- 2014/11/08: Two preprints published on arXiv illustrate the newest
  package features:
  - [*Spatio-Temporal Analysis of Epidemic Phenomena Using the R Package
    surveillance*](https://arxiv.org/abs/1411.0416)
  - [*Monitoring Count Time Series in R: Aberration Detection in Public
    Health Surveillance*](https://arxiv.org/abs/1411.1292)

## 2013

- 2013/04/23: [Talk](https://surveillance.R-forge.R-project.org/slides/StockholmR-Hoehle_4.pdf) at the Stockholm R useR
  group (StockholmR) on [Making R packages (and) Shiny](https://www.meetup.com/StockholmR/events/105738342/).

## 2011

- 2011/10/10-13: Lecture on *Temporal and spatio-temporal modelling of infectious
  diseases* at the Department of Statistics, University of Munich

## 2008

- 2008/11/27-28: Short-course on *Statistical surveillance of infectious diseases*
  held at the Department of Statistics, Universidade Federal de Minas Gerais
  (UFMG), Belo Horizonte, Brazil

- 2008/11/17: [Invited talk](https://surveillance.R-forge.R-project.org/slides/hoehle-surveillance.pdf) held at the 2008
  ESCAIDE satellite workshop on *Computer supported outbreak detection and signal
  management* ([R-File](https://surveillance.R-forge.R-project.org/slides/hoehle-surveillance.R), [Data](https://surveillance.R-forge.R-project.org/slides/ha.csv))
