---
title: "`surveillance`: Temporal and Spatio-Temporal Modeling and Monitoring of Epidemic Phenomena"
---

The open-source [R](https://www.R-project.org/) package **surveillance**
implements statistical methods for the *modeling* and *monitoring* of
epidemic phenomena based on (infectious disease) surveillance data.
This includes time series of counts, proportions and
categorical data as well as spatio-temporal point processes.

## Prospective Outbreak Detection

## Spatio-Temporal Endemic-Epidemic Modelling

## Modelling Structural Delays and Reporting Delays


## Installation

The stable release version of **surveillance** is hosted on the
Comprehensive R Archive Network (CRAN) at
<https://CRAN.R-project.org/package=surveillance>
and can be installed via

```R
install.packages("surveillance")
```

The development version of **surveillance** is hosted on R-Forge at
<https://R-Forge.R-project.org/projects/surveillance/> in a Subversion
(SVN) repository. It can be installed via

```R
install.packages("surveillance", repos = "https://R-Forge.R-project.org")
```


## Feedback

Contributions are welcome!
Please report bugs via e-mail to `maintainer("surveillance")`.

Note that (large) new features are unlikely to be included in **surveillance**.
Some extensions have already been developed in separate packages, for example
[**hhh4contacts**](https://CRAN.R-project.org/package=hhh4contacts),
[**HIDDA.forecasting**](https://hidda.github.io/forecasting/),
and [**hhh4addon**](https://github.com/jbracher/hhh4addon).


## Funding

The authors acknowledge financial support from the following institutions:

- [FAU Interdisciplinary Center for Clinical Research](https://www.izkf.med.fau.eu/)
  (IZKF, 2018-2021, junior project J75)
- [Swedish Research Council](https://www.vr.se/english.html) (VR, 2016-2019, #2015-05182)
- [Swiss National Science Foundation](http://www.snf.ch/en/) (SNSF, 2007-2010, 2012-2015, projects
  [#116776](http://p3.snf.ch/Project-116776),
  [#124429](http://p3.snf.ch/Project-124429), and
  [#137919](http://p3.snf.ch/Project-137919))
- [Munich Center of Health Sciences](https://www.en.mc-health.uni-muenchen.de/)
  (MC-Health, 2007-2010)
- [German Science Foundation](https://www.dfg.de/en/) (DFG, 2003-2006)


## License

The **surveillance** package is free and open-source software,
and you are welcome to redistribute it under the terms of the
[GNU General Public License, version 2](https://www.gnu.org/licenses/gpl-2.0.html).
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY. 
