################################################################################
### Author: Sebastian Meyer [sebastian *.* meyer *a*t* ifspm *.* uzh *.* ch]
### Time-stamp: <[simplification.R] by SM Mon 31/03/2014 12:34 (CEST)>
### Project: polygon simplification using www.MapShaper.org
################################################################################

library("sp")
load("kreise.RData")


### save as shapefile for import at www.MapShaper.org
### we use rgdal facilities (alternative: maptools::writeSpatialShape)

library("rgdal")
## GDAL: 1.10.0, released 2013/04/24
## PROJ.4: Rel. 4.8.0, 6 March 2012, [PJ_VERSION: 480]

writeOGR(kreise, dsn = ".", layer = "kreise", driver = "ESRI Shapefile")


### -> Go to www.MapShaper.org (v. 0.1.17)

## select method "modified Visvalingam" (others produce many line intersections)
## select options "prevent shape removal" and "repair intersections"
## import the shapefile
## select level of simplification
## export as shapefile


### import shapefiles generated by MapShaper.org

simplifications <- list.dirs(".", full.names=FALSE, recursive=FALSE)
kreiseSimple <- lapply(simplifications, function (dir) {
    res <- readOGR(dir, "kreise", verbose=TRUE)
    row.names(res) <- row.names(kreise)
    SpatialPolygonsDataFrame(
        SpatialPolygons(res@polygons, proj4string=kreise@proj4string),
        data = kreise@data
        )
})
names(kreiseSimple) <- sub("^kreise_", "", simplifications)
newOrder <- order(as.numeric(
    gsub("[a-z]", "", names(kreiseSimple), ignore.case=TRUE)
    ))
kreiseSimple <- kreiseSimple[newOrder]


### save

save(kreiseSimple, file="kreiseSimple.RData")
tools::resaveRdaFiles("kreiseSimple.RData")
